### ISSUE TITLE
Some @Param values can not be converted to target type: "CUCKOO8_4" can not be converted to org.minperf.bloom.Filter.Type

### ISSUE THREAD

**Issue by tchaye59** [thomasmueller/minperf#11]
I would like to test the minperf API but when I clone the project and open it, I have an error like **Some @Param values cannot be converted to target type: "CUCKOO8_4" cannot be converted to org.minperf.bloom.Filter.Type**.
**Please, How to solve this problem and compile the API?**

**Comment by thomasmueller** [comment]
Should be resolved now, could you check?

**Comment by tchaye59** [comment]
Thank you so much . My problem is solved.
