### ISSUE TITLE
hash48() implementation is the same as hash16().

### ISSUE THREAD

**Issue by sh1boot** [thomasmueller/minperf#13]
Looking here:
https://github.com/thomasmueller/minperf/blob/cc303690383fccfbeb769bdfd937b81e1e133ac1/src/main/java/org/minperf/utils/RandomSetGenerator.java#L170

Also, I have a list of parameters for different hash lengths here if you need it:
https://github.com/sh1boot/prpg/blob/e2d0a1c66359348c510819fb004b27e6f181499e/prpg.c#L104

**Comment by thomasmueller** [comment]
Thanks, and sorry for the delay! I will investigate.

**Comment by thomasmueller** [comment]
I removed hash48 https://github.com/thomasmueller/minperf/commit/eaaeb67ad64a29a2f2bba53ec500f60a2bcd4016 as it's currently not used. Feel free to submit patches / pull requests!

**Comment by sh1boot** [comment]
Well, picking from my table, the function would be:

    public static long hash48(long x) {
        x = (x ^ (x >>> 22)) * 0x43a812d4ed35L;
        x &= 0xffffffffffffL;
        x = (x ^ (x >>> 21)) * 0xa8f9d21b4457L;
        x &= 0xffffffffffffL;
        x = x ^ (x >>> 26);
        return x & 0xffffffffffffL;
    }

The magic numbers were found by [searches](https://sh1blog.blogspot.com/2016/08/n-bit-mixer-functions-eight-to-64-bits.html) for each bit length in the style of Murmur3 mix functions.  Take whatever you need.

But since the function isn't used I guess that doesn't help.  Also, I'm not sure how the operation fits in the bigger picture of what you're doing.  I found my way here from an article on generating permutations.

**Comment by thomasmueller** [comment]
Yes, I understand. I think it's great to have those values and algorithms! It's just, in this project, there was no code actually using or testing this method...  I think it would be nice to have those! But I'm afraid I currently don't have time to work on it. If you would like to add them, with link to the source article, that would be great! Also, the features could be extended.
