### ISSUE TITLE
Performance comparison to java.util.HashMap

### ISSUE THREAD

**Issue by gunnarmorling** [thomasmueller/minperf#15]
Hi, I'm not sure what's the best place to ask questions related to this project, so I hope it's ok if I create this issue to do so. 

I'm wondering whether you did any performance comparisons (in regards to look-up speed) to the JDK's `HashMap`. In a quick test I'm observing that `HashMap` is about 8x faster for `get()` than calling `RecSplitEvaluator#eval()`. Does this match your expectation, too, or am I doing some stupid mistake on my end?

I'm interested as I was hoping to use MinPerf as means to optimize through-put of look-ups in immutable maps I have; but perhaps I was misguided, and actually optimizing throughput isn't a goal for MinPerf, but it's (only) optimizing for space instead? In my case, space is not so much of an issue (maps are 10K entries at most), but accessing them as efficiently as possible is desirable. Thanks a lot for clarifying!

**Comment by thomasmueller** [comment]
HashMap to be 8x faster is about what I would expect as well, I'm afraid. Well, if give the minimal perfect hash function more space, then it would be faster; but it's very hard to reach the HashMap speed. I see the main use case for minimal perfect hashing is to saving space (memory), and not so much improving speed. Sure, speed needs to be acceptable.

If you want to speed up access to a hash map, and if you can live with some limitations, then you could maybe:
* Depending on the key, speed up, or completely avoid the "equals" check that is needed for a HashMap (in case of a hash collision).
* Use a different (faster) hash function, and store the hash value in the key, to avoid repeated calls to the hash function.

**Comment by gunnarmorling** [comment]
Ok, thanks a lot for clarifying, much appreciated.
