### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by joprice** [thomasmueller/minperf#17]
Does this data structure retain the keys used to create it? I am searching for a perfect hash map to avoid storing millions of string keys of about 250 characters in length that map to relatively small integers. I found this one, but it seems to keep the keys and do an equality check on lookup: https://github.com/haifengl/smile/blob/f597591d0b26d14dbeaa2fdc2b70b1448ee3c564/math/src/main/java/smile/hash/PerfectHash.java.

**Comment by thomasmueller** [comment]
> Does this data structure retain the keys used to create it?

No.

> I found this one, but it seems to keep the keys and do an equality check on lookup

Yes, this other one (based on the very old FKS algorithm) does.
